### ISSUE TITLE
Battery icon

### ISSUE THREAD

**Issue by ludenticus** [jkrajniak/gnome-shell-ext-icon-manager#3]
I was trying to move the battery icon to the tray panel, because mine is actually useless. If I thick it in the icon-manager, it behaves weird: instead of disappearing, it shows a larger icon. I am running the Fedora 15 repo (GS 3.0.1). It also shows a pop-up menu that corresponds to the tray panel, not the to top one.

Screenshot:
http://ubuntuone.com/p/1Em1/

**Comment by jkrajniak** [comment]
Please check new version.
