### ISSUE TITLE
doesn't work with gnome 3.2

### ISSUE THREAD

**Issue by SeniorSpielbergo** [jkrajniak/gnome-shell-ext-icon-manager#4]
I am using Arch Linux x686 with gnome 3.2 and tried to use this extension. I changed metadata.json to gnome 3.2, but the skript is not recognized by the system.

When I use ALT+F2 with "lg", it says that there is an init function missing in the skript.
When I add a dummy init() function, it says it needs an enable function. When I add a dummy enable() function, it says it needs an disable function.
When I add a dummy disable() function and try to use the extension it breaks the whole gnome session and I have to reset.

I think the main problem is, that they changed the whole way these extensions are written. This is proved by another extension "https://github.com/ecoleman/noa11y-colemando.com", which still has an error in it, but is working after changing it.

I'm not really into programming these extensions, so I have no idea how to change it.
Would be great, if you could have a look at it.

I hope these hints help finding the problem. Thanks in advance.

**Comment by benleb** [comment]
same problem, please help :) great extension and i miss it every minute :/

**Comment by jkrajniak** [comment]
new version should work on gnome 3.2
