### ISSUE TITLE
Use GNOME Shell extension settings pannel

### ISSUE THREAD

**Issue by llaumgui** [jkrajniak/gnome-shell-ext-icon-manager#9]
Hi,

why not use the GNOME Shell extension native setting pannel to configure gnome-shell-ext-icon-manager ?

Thx

**Comment by jkrajniak** [comment]
Yeah, I know, I work on it so for couple of days it should be here.

**Comment by jkrajniak** [comment]
Please check last update. I created simple settings panel.
